### PR TITLE
Direct users to file a bug report on build.Criticals

### LINKED ISSUE #1294: Direct users to submit github issues when a developer error is encountered
For example in siac when a 404 error is returned, print `"Please file a bug report on our GitHub: https://github.com/NebulousLabs/Sia/issues"` before the error message.

This could be added to `build.Critical` messages as well.

### PR DESCRIPTION
**Pull request by VoidingWarranties**
Closes #1294.

### CODE REVIEW

**Comment by lukechampine** [comment]
info should come after the actual error. e.g.
```
Loading...
(1/3) Loading gateway...
(2/3) Loading consensus...
(3/3) Loading explorer...
Finished loading in 0.028368234000000003 seconds
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
```

**Comment by VoidingWarranties** [comment]
Done. The Linux build is passing but OS X builds are stalling on Travis again.

**Comment by lukechampine** [comment]
Some sort of traceback would probably be useful, i.e. https://github.com/lukechampine/caller
Fine for now though.

**Comment by DavidVorick** [comment]
Some like 3 or 5 callstack lines deep would be good, don't want to overwhelm the user though

**Pull request merged**
