### PR TITLE
Allow for noninteractive startup when using API authentication

### PR DESCRIPTION
**Pull request by ericflo**
I've been working on automating my setup into a kubernetes cluster, and I want it to be secure even though it's automated. Currently Sia asks for a password in an interactive way, which is a showstopper for this project.

This patch adds the environment variable ``SIA_API_PASSWORD``. On startup if it's detected to be non-empty, that will be used instead of prompting the user. Just as with ``SIA_WALLET_PASSWORD`` it prints a line indicating that it has picked up the password from the environment -- so nobody should be caught off-guard.

### CODE REVIEW

**Comment by tbenz9** [comment]
Isn't this a duplicate of #2351?

**Comment by avahowell** [comment]
Not quite: this PR adds an option to set the API password noninteractively, the linked PR adds automatic wallet unlocking.

**Comment by lukechampine** [comment]
@ericflo Sorry for the delay; this LGTM. However, we'll need to fix the merge conflicts, which probably just means switching from `speakeasy` to `readPassword`.

**Comment by ericflo** [comment]
This should be good to go now. It's running live on SiaCDN now too.

**Comment by lukechampine** [comment]
Awesome, thanks!

**Pull request merged**
