### PR TITLE
Verify API security when host is blank

### PR DESCRIPTION
**Pull request by VoidingWarranties**
And do not verify API security in DEBUG mode. See commit message for reasoning.

### CODE REVIEW

**Comment by VoidingWarranties** [comment]
Do not merge yet

**Comment by VoidingWarranties** [comment]
Oh, I overlooked that disabling the check in DEBUG would break the tests. Hmm, maybe the convenience provided isn't enough reason.

**Comment by DavidVorick** [comment]
We need to be able to test this function, you can't disable it in testing.

Also, definitely need to extend the tests to show that the flag warning will trigger for `--api-addr :xxxx`

**Comment by DavidVorick** [comment]
Also, is it really that bad to add the --diable-api-security flag when using a docker container? Definitely not worth it.

**Comment by VoidingWarranties** [comment]
### Done
* Rebased
* Removed the commit that skipped security check in DEBUG
* Fixed tests
* Added an additional message to the error output if the host is blank e.g.
```
$ siad -d sia_test/ --api-addr 9980
an empty host will listen on all interfaces, did you mean localhost:9980?
you must pass --disable-api-security to bind Siad to a non-localhost address
```

### To do
* [ ] Consider special casing the `--api-addr` argument to default to `localhost` if the host is not specified.
    - should `x` default to `localhost:x`?
    - should `:x` default to `localhost:x`? This would make it impossible to listen on all interfaces. I'm not aware of a valid use case for this, but there might be.
* [ ] Update `TestUnitProcessNetAddr`, `TestUnitProcessConfig`, and `TestVerifyAPISecurity` accordingly.

**Pull request merged**
