### PR TITLE
Fix check on WindowEnd

### PR DESCRIPTION
**Pull request by nielscastien**

### CODE REVIEW

**Comment by nielscastien** [comment]
This fix prevents a renter from forming a new contract with a too long duration. As a hoster I would like to have this fixed asap ;-) @lukechampine

**Comment by lukechampine** [comment]
good catch!

**Comment by DavidVorick** [comment]
I don't think this is correct

**Comment by DavidVorick** [comment]
@lukechampine please be careful about merging anything related to verification or protocols, this stuff is security sensitive and I think this PR introduces a bug

**Pull request merged**
