### PR TITLE
Updates to Guide to Contributing to Sia

### PR DESCRIPTION
**Pull request by MSevey**
These are some edits that I found helpful when going through the Guide to Contributing to Sia and getting set up.

### CODE REVIEW

**Comment by lukechampine** [comment]
I think we can trim the `Install Go` section to just the first two paragraphs. Go assumes a default GOPATH of `~/go` now anyway, and the guide we link to tells people how to add `$GOPATH/bin` to their PATH.

**Comment by tbenz9** [comment]
Sorry to hijack this PR.

@MSevey Great to see your first contribution!  I tend to spend a fair amount of time reviewing GH issues and PRs, feel free reach out to me if you have any questions and don't want to bother Luke, David, or Chris.

**Comment by MSevey** [comment]
Hi @tbenz9 it's nice to e-meet you!

@lukechampine I trimmed the install go section per your request.

**Comment by lukechampine** [comment]
Woo!
One nitpick: commit messages should be written in imperative form (e.g. "Trim" instead of "Trimmed"). There's a good guide here: https://chris.beams.io/posts/git-commit (which we don't follow perfectly, but we make an effort).

**Pull request merged**
