### PR TITLE
Ignore IntelliJ IDEA files

### PR DESCRIPTION
**Pull request by bitspill**

### CODE REVIEW

**Comment by DavidVorick** [comment]
It seems odd to me that we would put Java IDE files in our .gitignore, but I don't see the harm in it.

We should probably add comments for the other ignored files.

Vim is '*.swp'

pdflatex is 'doc/' stuff.

cover and release are both folders that are created during different parts of the build process (cover measures test coverage, release contains cross-platform binaries)

**Comment by DavidVorick** [comment]
@lukechampine what are your thoughts?

**Comment by bitspill** [comment]
IntelliJ started out as a Java IDE but now they have plugins for "everything".

https://github.com/go-lang-plugin-org/go-lang-idea-plugin

**Comment by lukechampine** [comment]
I don't see any harm in merging this, esp. with comments.

**Pull request merged**
