### PR TITLE
Improvements to Transaction Pool (tpool) Module

### PR DESCRIPTION
**Pull request by willmadison**
This is just a placeholder for our conversation about work to be done to improve Sia's transaction pool such that it can safely support larger pools and ultimately be configurable by the user (long term the goal is to improve the minimum fee algorithm, add support for replace by fee and cP4P, and wallet based fee bumping all of which is dependent on an improved tpool).

### CODE REVIEW

**Comment by lukechampine** [comment]
Since there are multiple features we want to add, let's move this to an issue (or perhaps a project @DavidVorick) rather than a pull request. We like to keep our list of PRs small. Each feature will likely warrant its own PR.

**Comment by DavidVorick** [comment]
Sorry, we did not talk about this. @lukechampine I've directed people looking at contributing to open pull requests directly, because issues lately have been high in volume. Every pull request represents work in progress, and will give everyone a short list of what everyone else is working on.

I'm expecting to have 3-5 new contributors all working on new things, and this was my choice for product management.

Sorry that we did not discuss it first.

**Comment by DavidVorick** [comment]
For the formatting, we like to keep it 

stdlib

sialib

otherlib

Which goimports seems to not prefer. The file that got changed has them in the wrong order anyway, but the new changes do not match our other files

**Comment by lukechampine** [comment]
@DavidVorick I believe goimports does not actively split your imports except to separate stdlib from non-stdlib. If you manually insert extra line breaks, goimports will respect them.

**Pull request closed without merging**
