### PR TITLE
update README with build instructions

### PR DESCRIPTION
**Pull request by mtlynch**
Update README.md with instructions to build Sia from source.

### CODE REVIEW

**Comment by DavidVorick** [comment]
Hello! Nice to see a PR from you again

**Comment by DavidVorick** [comment]
I am not sure why your build is failing, I think it's related to travis maxing out the number of requests allowed for one of our dependencies, it downloads it every time. We should be able to have a fix in the next few days.

**Comment by DavidVorick** [comment]
Oh, it's because you aren't pushing from the Sia repo, the keys to get around the ratelimit only work for the Sia repo. I will fix this by moving your commit to a branch on our repo.

**Comment by mtlynch** [comment]
Closing as this has been moved to https://github.com/NebulousLabs/Sia/pull/1098

**Pull request closed without merging**
