### PR TITLE
add missing close(finishedChan) to threadedReceiveBlocks

### PR DESCRIPTION
**Pull request by johnathanhowell**

### CODE REVIEW

**Comment by lukechampine** [comment]
eesh, nice catch! Does this mean those conns were just hanging around until shutdown?

**Comment by johnathanhowell** [comment]
Seems like it

**Comment by DavidVorick** [comment]
The deadline should have killed it after long enough.

**Comment by lukechampine** [comment]
A deadline will cause the next read/write operation to return an error, but I'm not sure if it actually cleans up the underlying connection.

**Pull request merged**
