### PR TITLE
add wallet context support

### PR DESCRIPTION
**Pull request by avahowell**
This PR adds support in the wallet for contexts, as described in #2266. This lays the groundwork for the UX improvements outlined in #2246.

### CODE REVIEW

**Comment by lukechampine** [comment]
do we need api support for this yet? I think I'd prefer to leave that until later. Also, I think it's fine if `SendSiacoins` always uses the default context. If you want to use a custom context, use a transactionbuilder.

**Comment by DavidVorick** [comment]
Part of the purpose of writing proposals is to get reviews on the high-level ideas and design before writing the code, that way if substantial changes are made, you don't have to redo the coding bits

**Comment by lukechampine** [comment]
ah yeah, I should have commented on the proposal earlier

**Comment by avahowell** [comment]
Rebased and resolved merge conflicts.

**Pull request closed without merging**
