### PR TITLE
new google analytics

### PR DESCRIPTION
**Pull request by seveibar**

### CODE REVIEW

**Comment by seveibar** [comment]
fixes #255

**Comment by DavidVorick** [comment]
"can't automatically merge this pr"

You've got a merge conflict, need to resolve that and re-push

**Comment by seveibar** [comment]
man google analytics are so hard

**Comment by DavidVorick** [comment]
don't look now but you messed up the tabbing :P

**Comment by seveibar** [comment]
I give up haha

**Comment by DavidVorick** [comment]
You gotta slow down a bit and check for mistakes before you PR

**Pull request merged**
