### PR TITLE
add glyphcheck to Travis

### PR DESCRIPTION
**Pull request by lukechampine**
Once this is merged, #1703 should fail. :)

### CODE REVIEW

**Comment by DavidVorick** [comment]
#1703 already fails.

**Comment by DavidVorick** [comment]
Glyphcheck repo needs a test suite. Also, does it only check for the homoglyphs, but leaves all other glyphs behind as okay?

**Comment by lukechampine** [comment]
I suppose it already fails, but now it will fail earlier.
It only checks for homoglyphs. This reduces the number of false positives in non-english code. Perhaps we could use a flag to enable strict ASCII-only mode.

**Comment by VoidingWarranties** [comment]
#1703 only fails because I wrote the test for it the week prior ;)

**Comment by DavidVorick** [comment]
pretty sure it does not check the dependencies. It is a good thought that we should be vendoring them and checking them, but that's too big of a change for now.

Fwiw I'm pretty sure @johnathanhowell ran this check over a ton of repos and nothing came up. I know that's not the same as checking every dependency every time something changes, but it's some initial piece of mind.

I think we're good to merge this for now, and we can make an issue to automate checking our deps from a different PR.

**Pull request merged**
