### PR TITLE
Fix documentation error in /wallet/transaction/id

### PR DESCRIPTION
**Pull request by NickvanDyke**

### CODE REVIEW

**Comment by lukechampine** [comment]
I think the documentation is actually correct here.`/wallet/transaction/id` returns a JSON object containing a "transaction" field, which is a `modules.ProcessedTransaction` that itself contains a "transaction" field.

It's ugly but it was written this way so that we could easily add more data to the response later without altering `modules.ProcessedTransaction`. Perhaps it would have been better to embed the `modules.ProcessedTransaction`, but we can't do that now without breaking API compatibility.

**Comment by DavidVorick** [comment]
@NickvanDyke can you show the json object you showed me that was returned?

**Comment by NickvanDyke** [comment]
I don't have access to the computer it's on right now, I'll put it up here later tonight.

@lukechampine The responses I've been getting for transactions only have one transaction key, which is mapped to the raw data. There aren't two transaction keys, one of which contains every other key, as the documentation suggests

**Comment by NickvanDyke** [comment]
@lukechampine @DavidVorick The response I was getting from querying an actual transaction. Similar format as every transaction response I got.

````
{
   "transaction":{
      "siacoininputs":[
         {
            "parentid":"5ec0c69f12b9bb569c24f08a1811da0b14106ef23e71f776ae8a72729bc18e3c",
            "unlockconditions":{
               "timelock":0,
               "publickeys":[
                  {
                     "algorithm":"ed25519",
                     "key":"GMv2Hyf528arZK2OKJYGdvKqAu772HLMBen2pJRR3G4="
                  }
               ],
               "signaturesrequired":1
            }
         }
      ],
      "siacoinoutputs":[
         {
            "value":"50000000000000000000000000",
            "unlockhash":"3d17fc06d0a6dfed948a9eb6cddb11317e39e408897a26eea3c78c70bcb6816954cc4a02f4be"
         }
      ],
      "filecontracts":null,
      "filecontractrevisions":null,
      "storageproofs":null,
      "siafundinputs":null,
      "siafundoutputs":null,
      "minerfees":[
         "750000000000000000000000"
      ],
      "arbitrarydata":null,
      "transactionsignatures":[
         {
            "parentid":"5ec0c69f12b9bb569c24f08a1811da0b14106ef23e71f776ae8a72729bc18e3c",
            "publickeyindex":0,
            "timelock":0,
            "coveredfields":{
               "wholetransaction":true,
               "siacoininputs":null,
               "siacoinoutputs":null,
               "filecontracts":null,
               "filecontractrevisions":null,
               "storageproofs":null,
               "siafundinputs":null,
               "siafundoutputs":null,
               "minerfees":null,
               "arbitrarydata":null,
               "transactionsignatures":null
            },
            "signature":"INRHPzT9ZSTPqWKFfDzcsocf8Yvi61gqa\/8OzQbBT7q4o7p5aHPmYhgksiiuIfdO7Yxg4UEPvnCSppJdOtJvBQ=="
         }
      ]
   },
   "transactionid":"60958bc351ac183c5121304bd4fa1c29f9fe80ca29e175ad1c468fe689eeabee",
   "confirmationheight":107779,
   "confirmationtimestamp":1496461054,
   "inputs":[
      {
         "parentid":"5ec0c69f12b9bb569c24f08a1811da0b14106ef23e71f776ae8a72729bc18e3c",
         "fundtype":"siacoin input",
         "walletaddress":false,
         "relatedaddress":"8a9d8e6c8d043300b967443eaaa01874efa36e69a95b03c6b970bfe5b82a7f0345424a7919af",
         "value":"50750000000000000000000000"
      }
   ],
   "outputs":[
      {
         "id":"b7b6125c8ce09255256ed8fa268670a6b30d948895b976117e10738db70ba830",
         "fundtype":"siacoin output",
         "maturityheight":107779,
         "walletaddress":true,
         "relatedaddress":"3d17fc06d0a6dfed948a9eb6cddb11317e39e408897a26eea3c78c70bcb6816954cc4a02f4be",
         "value":"50000000000000000000000000"
      },
      {
         "id":"0000000000000000000000000000000000000000000000000000000000000000",
         "fundtype":"miner fee",
         "maturityheight":0,
         "walletaddress":false,
         "relatedaddress":"000000000000000000000000000000000000000000000000000000000000000089eb0d6a8a69",
         "value":"750000000000000000000000"
      }
   ]
}
````

**Comment by lukechampine** [comment]
I can't reproduce this. The structure I get is:
```
{
   "transaction": {
      "transaction": {
         "siacoininputs": [
            < omitted >
         ]
      },
      "transactionid": < omitted >,
      "confirmationheight": < omitted >,
      "confirmationtimestamp": < omitted >,
      "inputs": [
         < omitted >
      ],
      "outputs": [
         < omitted >
      ]
   }
}
```
The call I used was:
```
curl -A "Sia-Agent" 'localhost:9880/wallet/transaction/<txid>'
```

**Pull request closed without merging**
