### PR TITLE
Move block check functions to modules/consensus

### PR DESCRIPTION
**Pull request by mtlynch**
Move block checking functions to modules/consensus as part of an effort
to pull complexity out of types.Block and make code that depends on
types.Block more testable.

### CODE REVIEW

**Comment by DavidVorick** [comment]
@mtlynch we fixed the muxado errors that caused the build to frequently fail. If you merge the latest changes it won't be an issue for your PR anymore

**Comment by lukechampine** [comment]
muxado fix is in the repairing branch, so that needs to be merged first

**Comment by DavidVorick** [comment]
Pretty simple change, looks good to me without any further changes.

**Comment by mtlynch** [comment]
Passing now.

I changed it slightly because miner/blockmanager.go now depends on `CalculateSubsidy` so I've left that function where it is for now.

**Pull request merged**
