### PR TITLE
Set pre-hardfork host score to 0

### PR DESCRIPTION
**Pull request by ChrisSchinnerl**

### CODE REVIEW

**Comment by lukechampine** [comment]
I think it's illegal to set the weight to 0. You can only set it to a very, very small value.

**Comment by ChrisSchinnerl** [comment]
@lukechampine challenge accepted

**Comment by lukechampine** [comment]
looks like there's a separate constant for that: `math.SmallestNonzeroFloat64`.
this is fine though

**Comment by DavidVorick** [comment]
```
=== RUN   TestHostWeightDistinctPrices
--- FAIL: TestHostWeightDistinctPrices (0.00s)
	hostweight_test.go:27: 1
	hostweight_test.go:28: 1
	hostweight_test.go:29: Weight of expensive host is not the correct value.
=== RUN   TestHostWeightIdenticalPrices
--- PASS: TestHostWeightIdenticalPrices (0.00s)
=== RUN   TestHostWeightWithOnePricedZero
--- FAIL: TestHostWeightWithOnePricedZero (0.00s)
	hostweight_test.go:51: Zero-priced host should have higher weight than nonzero-priced host.
=== RUN   TestHostWeightWithBothPricesZero
```

**Pull request merged**
