### PR TITLE
force api authentication if --disable-api-security

### PR DESCRIPTION
**Pull request by DavidVorick**
siac has no support for api authentication, and I would like to write
some additional tests around the logic. Would also like to convert the
error messages in to explicit variables the way that we have for most of
the modules.

### CODE REVIEW

**Comment by DavidVorick** [comment]
this should have more tests before being merged

**Comment by DavidVorick** [comment]
This is necessary to protect miners. The miners in our ecosystem, even after upgrading to 1.0, are still largely using the `--disable-api-security` flag without setting up any sort of additional security, leaving themselves vulnerable to having their coins stolen. Then the miners blame us, and the thieves sell the coins, and the price drops, and the traders get mad too.

It's not really our fault, but I think we can at least do a little more to protect our miners.

**Comment by VoidingWarranties** [comment]
siac does support API authentication

**Comment by DavidVorick** [comment]
running `siac -h` does not display anything which indicates support for api authentication

**Comment by lukechampine** [comment]
It could be clearer, yeah. IIRC the current behavior is that siac will try to make the call without auth, then fallback to a password prompt if it gets an "auth required" response.

**Comment by DavidVorick** [comment]
oh hmm, that does allow you to protect the password with speakeasy

**Comment by DavidVorick** [comment]
should be good now

**Pull request merged**
