### PR TITLE
File sharing feature

### PR DESCRIPTION
**Pull request by tlightsky**
implement this feature by these steps:
#1 use shareAscii to share file,contracts with publickey 
#2 use loadShareAscii to load share info on another renter 
#3 check publickeys is sufficient to download or not ,if not form new download only contracts
#4 use renter download to download loaded file (with setallowance before)

### CODE REVIEW

**Comment by CarloPalinckx** [comment]
You should consider turning those vars into consts

**Comment by tlightsky** [comment]
rebased to current master

**Comment by tlightsky** [comment]
rebased to current master

**Comment by tlightsky** [comment]
seems a wrong rebase happen, try to fix it

**Pull request closed without merging**
