### PR TITLE
Some NDFs

### PR DESCRIPTION
**Pull request by DavidVorick**

### CODE REVIEW

**Comment by lukechampine** [comment]
Is this a WIP?

**Comment by DavidVorick** [comment]
It should be complete at this point

**Comment by DavidVorick** [comment]
Pushed 2 more ndf fixes because they were within reach.

**Comment by lukechampine** [comment]
I've restarted this 4 times and both builds have failed, for different reasons, every time :|

**Comment by DavidVorick** [comment]
We just have to keep grinding through them I think. Frustrating that the tests are so much more reliable locally, but I think we'll get through these soon enough. We're doing a good job fixing a few every PR. There are a finite number.

**Pull request merged**
