### PR TITLE
bump host leeway to 0.0035

### LINKED ISSUE #2223: Renter hostPriceLeeway is not enough leeway
See #2222. The specific numbers are:

| Host expects           | Renter requests        | Delta   |
|------------------------|------------------------|---------|
| 1124335615982010630144 | 1125575207576657461341 | + 0.11% |
| 1249164705177190531072 | 1250542223351996527544 | + 0.11% |
| 1249261795547560280064 | 1250639119541625537038 | + 0.11% |
| 1249455976288299778048 | 1250542223351996527544 | + 0.08% |
| 1249455976288299778048 | 1250639119541625537038 | + 0.09% |
| 1249747247399409025024 | 1250542223351996527544 | + 0.06% |
| 1262174814806736896000 | 1263526312762283799719 | + 0.10% |
| 1267417694806703341568 | 1268758707002250312387 | + 0.10% |
| 1394052664836168351744 | 1395527991850038481000 | + 0.10% |
| 2186208142208230490112 | 2188618459197844689817 | + 0.11% |
| 2217980965911730847744 | 2220327737253938046677 | + 0.10% |
| 2373412939825869225984 | 2376030224357988717524 | + 0.11% |
| 2498717771835860058112 | 2501084446703993055089 | + 0.09% |
| 3123154488868900700160 | 3126597798854063842596 | + 0.11% |
| 3170971496276002078720 | 3171896767505625780968 | + 0.02% |
| 3747494115531571593216 | 3751626670055989582633 | + 0.11% |
| 3747785386642680840192 | 3751917358624876611115 | + 0.11% |
| 3785068088864664453120 | 3787962741166868142825 | + 0.07% |
| 4435961931823461695488 | 4440655474507876093355 | + 0.10% |
| 4999765712560594092032 | 5002168893407986110178 | + 0.04% |
| 5046757451819552604160 | 5052167327256555009001 | + 0.10% |
| 5063068634041670434816 | 5064570039529068224213 | + 0.02% |
| 5069282417745334370304 | 5074647243250485211573 | + 0.10% |
| 6246308977737801400320 | 6253195597708127685192 | + 0.11% |
| 9467039288882829983744 | 9477174067193934591728 | + 0.10% |

I'm not sure if this is just an isolated incident, but in any case I don't think it would hurt to increase the leeway from `0.002` to `0.0035`.

### PR DESCRIPTION
**Pull request by lukechampine**
Fixes #2223

### CODE REVIEW

**Comment by DavidVorick** [comment]
Were there bugs seen in the wild caused by the low host leeway? 0.002 allows for a difference of up to 12 blocks, which should be more than enough already

**Comment by lukechampine** [comment]
yes, #2222

**Comment by lukechampine** [comment]
Maybe when this happens we should log what the renter thinks the blockheight is? Then we could tell whether it's caused by the renter lagging behind or some other problem.

**Comment by lukechampine** [comment]
closing until we get more reports of this bug. 0.002 ought to be enough

**Pull request closed without merging**
