### PR TITLE
adding 'expected behavior' to bug report template

### PR DESCRIPTION
**Pull request by tbenz9**

### CODE REVIEW

**Comment by lukechampine** [comment]
It seems like very few people are filling out the template properly. Wonder if there's something we can do about that.

**Comment by tbenz9** [comment]
@lukechampine, We could add instructions to the beginning of the template, this has a chance of just adding more cruft to each issue, or helping people use it more effectively.  It's probably worth a try.

Here's a sample of a big project using templates for bug/feature requests.  They offer clear instructions.
https://github.com/kubernetes/kubernetes/issues/new

**Comment by lukechampine** [comment]
Ah, looks like the kubernetes template puts the instructions inside `<!--` tags, which means they're hidden when rendered, even if the user forgets to delete them. We should do the same.

**Comment by tbenz9** [comment]
Sounds good, PR coming in a few hours.

**Pull request merged**
