### PR TITLE
resolve divide by zero in siac

### PR DESCRIPTION
**Pull request by DavidVorick**

### CODE REVIEW

**Comment by DavidVorick** [comment]
added another commit to eliminate a confusing 'total score' report. Normalizations can change from query to query, which means a normalized total score could jerk around a lot. Better I thought to just remove it entirely, and let the user compare the total score by looking at all the hosts. Score, all by itself, does not have much meaning.

**Comment by lukechampine** [comment]
I forget, why does this code use `big.Float` instead of `big.Rat`?

**Comment by DavidVorick** [comment]
I.... am not sure.

**Comment by DavidVorick** [comment]
will update I guess

**Pull request merged**
