### PR TITLE
move renter consts to consts.go

### PR DESCRIPTION
**Pull request by lukechampine**

### CODE REVIEW

**Comment by lukechampine** [comment]
appveyor does not seem to like the new test constants. Hmm.

**Comment by lukechampine** [comment]
okay. I've narrowed it down to `repairQueueInterval`. Appveyor does not like it when the `repairQueueInterval` is short enough that it runs during the test.
That actually seems like a bug worth investigating. It's weird that it only happens on appveyor, but maybe it can be triggered on Travis as well if we reduce the interval even more.

**Comment by DavidVorick** [comment]
That does seem like something worth investigating.  I'll merge it for now but I'll also make an issue for it.

**Comment by lukechampine** [comment]
nooo those ugly commits

**Comment by DavidVorick** [comment]
ah shoot. sorry about that

**Pull request merged**
