### PR TITLE
Changed instances of "spendCoins" to "sendCoins" 

### LINKED ISSUE #598: Spend Coins vs. Send Coins
in some places, we 'spend coins', and in others, we 'send coins', but they mean the same thing.

In all places, we should use the same vocabulary. My vote is to 'send coins'

### PR DESCRIPTION
**Pull request by Mingling94**
Fix #598 through simple find & replace

Replica of #600 except on NebulousLabs repo

### CODE REVIEW

**Comment by lukechampine** [comment]
pls squash those commits together. (`git reset --soft HEAD^ && git commit --amend`)

also, are we renaming the siafunds stuff as well? `SpendSiafunds`, etc

**Comment by DavidVorick** [comment]
we should rename the siafunds stuff too @Mingling94

**Comment by lukechampine** [comment]
ok, make sure the API call (`/wallet/siafunds/spend`) is updated, and API.md as well.

**Comment by Mingling94** [comment]
Check my last commit message. You can grep for over 150 instances of the word 'spend' even though its definition is almost the same as send.

**Comment by DavidVorick** [comment]
bump

**Comment by Mingling94** [comment]
Undid the change Luke commented on.

I'm not sure about changing the ~150 instances of the word "spend", so is this good for now?

Waiting for TravisCI though >.>

**Comment by Mingling94** [comment]
Merge this PR?

**Pull request merged**
