### PR TITLE
Decrypt chunk pieces in parallel and in-place

### PR DESCRIPTION
**Pull request by ChrisSchinnerl**
Encrypting/Decrypting a whole chunk with a single thread is pretty slow. This PR moves that code to the worker threads to encrypt/decrypt on a per-piece basis.

### CODE REVIEW

**Comment by lukechampine** [comment]
are there places where we don't want to decrypt in-place?

**Comment by ChrisSchinnerl** [comment]
@lukechampine It looks like quite a few tests in the wallet are failing if I change it to be in-place by default.

**Comment by DavidVorick** [comment]
Need to add a new function to the encryption package that does encryption in-place. Then only have that function be called in the renter so that compatibility in the other places that we use encryption is not threatened.

**Comment by ChrisSchinnerl** [comment]
I reverted the commits for the parallel encryption for now since it is just too much of a hack to do it in-place right now. Once we get rid of the nonce in the sector after moving to Threefish, we can implement a much easier in-place solution for this.

**Pull request merged**
