### PR TITLE
implement LTS release fetching

### PR DESCRIPTION
**Pull request by lukechampine**
note the assumptions made about the lts tag format.

### CODE REVIEW

**Comment by DavidVorick** [comment]
Seems good to me. If we sort alphabetically:

lts-v1.3.2
lts-v1.0.4
v1.4.3
v1.4.2
v1.4.1
etc

Makes the LTS really easy to find.

**Comment by lukechampine** [comment]
Another thing I realized is that this commit will need to be added to every lts branch. Alternatively, we could have only a single lts branch. That would be fine if LTSs never overlap.

**Comment by DavidVorick** [comment]
I was definitely thinking that we only have a single LTS branch.

Large upgrades (e.g. 1.0.4 -> 1.3.1) might be rough, but if we're careful with how we backport, I think we can avoid headaches.

**Comment by DavidVorick** [comment]
I think we should change the parent branch to `lts`, directly forked from our current master.

**Comment by lukechampine** [comment]
ok. After this PR is merged I'll rename the branch. (Easier than closing+reopening)

**Pull request merged**
