### PR TITLE
add progress to siac renter download

### PR DESCRIPTION
**Pull request by lukechampine**
Perhaps later on we can add an animated download bar, e.g. https://github.com/cheggaaa/pb

### CODE REVIEW

**Comment by lukechampine** [comment]
looks like we're hitting an internal error on appveyor:

>ERR Error running script (call to f_5b8e3b60e050400311bc8b6ef2cbba37bc0b9cb3): @user_script:1: @user_script: 1: -OOM command not allowed when used memory > 'maxmemory'.

**Comment by lukechampine** [comment]
Sample output:
```
luke@mjolnir:~$ siac renter download foo.mkv bar.mkv
Downloading... 100.0% of 266.36 MB, 45s elapsed, 47.31 Mbps     
Downloaded 'foo.mkv' to /home/luke/bar.mkv.
```

**Comment by lukechampine** [comment]
travis keeps failing :/ lots of "block does not extend the longest fork" errors

**Comment by DavidVorick** [comment]
That bug has been around for a while, but ultimately pretty elusive because whenever we start debugging inevitably it becomes unreproducible.

What is the max memory? Perhaps we are running out b/c something in the download code is using a ton of RAM?

**Pull request merged**
