### PR TITLE
add string spellchecking to the build

### PR DESCRIPTION
**Pull request by mtlynch**
Adding a spellcheck step to the build to catch misspelled words in comments and
output strings.

Fixing all of the existing spelling errors.

### CODE REVIEW

**Comment by lukechampine** [comment]
From what I recall, `misspell` doesn't catch *all* spelling errors, just most of the common ones.
I could see this being frustrating for people who make a PR and only find out much later that the build failed due to a spelling error. On the other hand, I really do prefer the code to be free from spelling errors. Ideally everyone would run this as a pre-commit hook, but there's no way to enforce that.

I also notice that a lot of the misspellings are just British variants. Not sure if enforcing American spelling is necessary. Is there a way we can accept both?

**Comment by mtlynch** [comment]
>I could see this being frustrating for people who make a PR and only find out much later that the build failed due to a spelling error. On the other hand, I really do prefer the code to be free from spelling errors. Ideally everyone would run this as a pre-commit hook, but there's no way to enforce that.

Up to you guys. If you want, I can pull out the `Makefile` changes and just leave the spelling corrections.

>I also notice that a lot of the misspellings are just British variants. Not sure if enforcing American spelling is necessary. Is there a way we can accept both?

Sure, I removed the US locale preference, so now it accepts US or UK spellings. As a check, I also changed it back to "optimi**s**ing**" in `vendor/github.com/pkg/errors/bench_test.go` and `misspell` is cool with it.

**Comment by mtlynch** [comment]
ping

**Comment by lukechampine** [comment]
I think we can accept this, but without `spellcheck` being required on `test-long` and `test-vlong`. I'm on  the fence about it, but we can always decide later whether to require it for PRs and such. For now, just having it as a makefile target is sufficient.

**Comment by mtlynch** [comment]
Okay, updated.

**Comment by lukechampine** [comment]
thanks!

**Pull request merged**
